In [1]:
# Выполним инициализацию основных используемых модулей
%matplotlib inline

import random
import matplotlib.pyplot as plt
from sklearn.preprocessing import normalize
import numpy as np

In [2]:
from sklearn.datasets import load_digits 

In [3]:
digits = load_digits()

In [4]:
X = digits.data
y = digits.target

In [9]:
X_train = X[:int(X.shape[0]*.75),:]
y_train = y[:int(X.shape[0]*.75)]

X_test = X[int(X.shape[0]*.75):,:]
y_test = y[int(X.shape[0]*.75):]

In [25]:
x = X_test[0]
x

array([ 0.,  0.,  7., 16., 16., 14.,  0.,  0.,  0.,  0., 16., 12., 10.,
       15.,  1.,  0.,  0.,  0., 10.,  4., 16., 10.,  0.,  0.,  0.,  0.,
        0.,  9., 16., 11.,  1.,  0.,  0.,  0.,  0.,  0.,  7., 16.,  8.,
        0.,  0.,  0.,  0.,  0.,  0., 16.,  7.,  0.,  0.,  0.,  8.,  4.,
       10., 15.,  2.,  0.,  0.,  0., 12., 16., 16.,  6.,  0.,  0.])

In [27]:
X_test

array([[ 0.,  0.,  7., ...,  6.,  0.,  0.],
       [ 0.,  0., 12., ...,  0.,  0.,  0.],
       [ 0.,  0.,  5., ..., 14.,  3.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [32]:
np.sum((X_test-x)**2, axis = 1), y_test

(array([   0., 2593.,  854.,  641., 3236., 2468., 2564., 2829., 3687.,
        1119., 2748., 1714., 1868.,  981., 2193., 2046., 2127., 1632.,
        1801., 1738., 2414., 2439., 2688.,  753., 2157., 2300., 2704.,
        3360., 3676.,  837., 2657., 1084., 1158., 3144., 2052., 3069.,
        1715., 3113.,  307., 3097., 3356., 1966., 2651., 1046., 2824.,
         923., 2447., 3030., 2459., 1966., 3368., 3290., 2102., 2154.,
        1433., 1803., 2039., 1856., 2196., 1255., 1834., 3200., 2560.,
        2599., 3773., 1402., 2099., 2006., 1519., 1618., 2344.,  873.,
        3299., 1271., 2795., 2302.,  997.,  742., 1626., 1940., 2938.,
         590., 3331., 1039., 2691., 2335., 1364.,  645., 1754., 2341.,
        2742., 1005., 3344., 2043., 2959., 2408., 1505.,  946., 2040.,
         693., 1146., 1105., 2645., 1083., 1821.,  540., 1652.,  681.,
        1265., 3331., 2225., 1931., 1979.,  991.,  795., 2223., 1824.,
        1742., 2234., 2230., 2901., 2097., 2327., 2148., 1877., 2315.,
      

In [13]:
X_test[0]*np.ones(X_test.shape[1])

array([ 0.,  0.,  7., 16., 16., 14.,  0.,  0.,  0.,  0., 16., 12., 10.,
       15.,  1.,  0.,  0.,  0., 10.,  4., 16., 10.,  0.,  0.,  0.,  0.,
        0.,  9., 16., 11.,  1.,  0.,  0.,  0.,  0.,  0.,  7., 16.,  8.,
        0.,  0.,  0.,  0.,  0.,  0., 16.,  7.,  0.,  0.,  0.,  8.,  4.,
       10., 15.,  2.,  0.,  0.,  0., 12., 16., 16.,  6.,  0.,  0.])

In [37]:
def nearest_1(X, y, x):
    X_ = X.copy()
    X_ = np.sum((X_-x)**2, axis = 1)
    return y[X_.argmin()]

In [53]:
y_prediction = [nearest_1(X_train, y_train, x) for x in X_test]
accuracy_score(y_test, y_prediction)

0.9622222222222222

In [47]:
def write_answer(problem, answear):
    with open("pa_5.3_"+str(problem)+'.txt', "w") as fout:
        fout.write(str(answear))

In [57]:
accuresy = sum([1. if pair[0] == pair[1] else 0. for pair in zip(y_prediction, y_test)])/len(y_prediction)
write_answer(1, 1-accuresy)

In [58]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
clf = RandomForestClassifier(n_estimators=1000)
clf.fit(X_train, y_train)
y_predict = clf.predict(X_test)
accuracy_score(y_test, y_predict)
write_answer(2, 1-accuracy_score(y_test, y_predict))